void main (){

  String ilce = "haliliye";
  print("İlçe Adı: $ilce");
  String kita = "Avrupa";
  print("Kıta Adı: $kita");
  int faks = 2555564;
  print("Faks No: $faks");
  int postaKodu = 63040;
  print("Posta Kodu: $postaKodu");
  String insta = "@cbrlkskndg";
  print("İnstagram: $insta");
  String bolum = "Mobil Developer";
  print("Çalıştığın Bölüm: $bolum");
  int urunMiktari = 150;
  print("Ürün Miktarı: $urunMiktari");
  String musteriSoyadi = "Çelik";
  print("Müşterinin Soyadı: $musteriSoyadi");
  double odemeMik = 150000;
  print("Ödeme Miktarı: $odemeMik TL");
  var dogumTarihi = DateTime(1997, 12, 29);
  print("Doğum Tarihi: $dogumTarihi");
  int borc = 30000;
  print("Borç: $borc TL");
  String medeniHal = "Bekar";
  print("Medeni Durumu: $medeniHal");
  String videoYorumu = "Güzel paylaşım";
  print("Video Yorumu: $videoYorumu");
  var odemeSaati = Duration(hours: 16, minutes: 30);
  print("Ödeme Saati: $odemeSaati");
  int eft = 32512;
  print("EFT Miktarı: $eft TL");
  int satilanMiktar = 65;
  print("Satılan Miktar: $satilanMiktar");
  String tlfModel = "iphone";
  print("Telefon Modeli: $tlfModel");
  String dergiAdi = "Sarmaşık";
  print("Dergi Adı: $dergiAdi");
  var basimTarihi = DateTime.utc(2021, 11, 9);
  print("Basım Tarihi: $basimTarihi");
  int zamMik = 12;
  print("Zam Miktarı: %$zamMik");
  int daireSayisi = 23;
  print("Daire Sayısı: $daireSayisi");
  int enlem = 46;
  print("Enlem: $enlem");
  int boylam = 25;
  print("Boylam: $boylam");
  String yemekAdi = "Lahmacun";
  print("Yemek Adı: $yemekAdi");
  double urunFiyati = 29.99;
  print("Ürün Fiyatı: $urunFiyati TL");
  String sirket = "Şanlı Yazılım";
  print("Şirket: $sirket");
  String videoAdi = "Dart Eğitim";
  print("Video Adı: $videoAdi");
  var muzikSuresi = Duration(minutes: 3, seconds: 32);
  print("Müzik Süresi: $muzikSuresi");
  int mekanPuani = 7;
  print("Mekan Puanı: $mekanPuani/10");
  String dosyaAdi = "Ödevler1";
  print("Dosya Adı: $dosyaAdi");
  String resimFormati = ".jpg";
  print("Resim Formatı: $resimFormati");
  String renk = "Sarı";
  print("Renk: $renk");
  String renkKodu = "#ffffff";
  print("Renk Kodu: $renkKodu");
  String bilModeli = "Notepad";
  print("Bilgisayar Modeli: $bilModeli");
  var ekranBoy = 6.9;
  print("Ekran Boyutu: $ekranBoy inc");
  var kulSuresi = Duration(hours: 2, minutes: 25, seconds: 30);
  print("Kullanım Süresi: $kulSuresi");
  var etkinlikGunu = DateTime(2023, 11, 9);
  print("Etkinlik Günü: $etkinlikGunu");
  var odemeGunu = DateTime(2023, 6, 23);
  print("Ödeme Günü: $odemeGunu");
  var yolCikisTar = DateTime(2023, 10, 24);
  print("Yola Çıkış Tarihi: $yolCikisTar");
  String mahalle = "Karşıyaka";
  print("Mahalle Adı: $mahalle");
  String otoHatti = "55";
  print("Otobüs Hattı: $otoHatti");
  var kulDk = Duration(minutes: 25, seconds: 54);
  print("Kullanılan Dakika: $kulDk");
  int kargoTakip = 8546856;
  print("Kargo Takip No: $kargoTakip");
  var kuponSuresi = Duration(hours: 5, minutes: 30);
  print("Kupon süresi: $kuponSuresi");
  String kuponKodu = "A65S4D5AS";
  print("Kupon Kodu: $kuponKodu");
  var faturaTarihi = DateTime(2023, 12, 15);
  print("Fatura Tarihi: $faturaTarihi");
}